config/routes.rb
Effy::Application.routes.draw do
  root :to => 'tasks#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/tasks/category/:category' => 'tasks#task_input', :as => :task_type
  get '/tasks/categories' => 'tasks#categories'
  get '/tasks/categories/all' => 'tasks#categories_all'
  get '/tasks/:category/tasks_by_category' => 'tasks#index_by_category', :as => :index_category
  get '/tasks/archives' => 'tasks#archives'
  get '/tasks/archives/all' => 'tasks#archives_all'
  get '/tasks/archives/:category' => 'tasks#archive_by_category'


  get '/tasks/:id/completed' => 'tasks#completed', :as => 'task_completed'
  get '/tasks/:id/uncompleted' => 'tasks#uncompleted', :as => 'task_uncompleted'
  # get '/' => 'tasks#new'
  resources :tasks, :users

  get '/404' => 'tasks#error_test'
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  description :string(255)
#  user_id     :integer
#  completed   :boolean
#  category    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Task < ActiveRecord::Base
    attr_accessible :description, :user_id, :completed, :category
    belongs_to :user
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :check_if_logged_in, :except => [:home]
  before_filter :check_if_admin, :only => [:index]

  def home
       
  end

  def index
    @tasks = Task.where(:user_id => @current_user.id, :completed => false)
  end

  def create
    task = Task.new params[:task]
    task.user_id = @current_user.id
    task.completed = false
    task.save
    redirect_to task
  end

  def new
    #raise params.inspect
    @task = Task.new
  end

  def edit
    @task = Task.find params[:id]
  end

  def show
    @task = Task.find params[:id]
  end

  def update
    task = Task.find params[:id]
    task.update_attributes(params[:task])
    redirect_to task
  end

  def destroy
    task = Task.find params[:id]
    task.update_attributes(params[:task])
    redirect_to task
  end

  def task_input
    @category = params[:category].split('?')[0]
    if params[:category].split('?')[1]
      @task = Task.find params[:category].split('?')[1]
    else
      @task = Task.new
    end
  end

  def categories
    
  end

  def index_by_category
    @tasks_by_category = Task.where(:user_id => @current_user.id, :category => params[:category], :completed => false)
  end

  def categories_all
    @tasks = Task.where(:user_id => @current_user.id, :completed => false)
  end

  def completed
    task = Task.find params[:id]
    task.completed = true
    task.save
    redirect_to new_task_path
  end

  def uncompleted
    task = Task.find params[:id]
    task.completed = false
    task.save
    redirect_to new_task_path
  end

  def archives
    
  end

  def archive_by_category
    @archive_by_category = Task.where(:user_id => @current_user.id, :category => params[:category], :completed => true)
  end

  def archives_all
    @tasks = Task.where(:user_id => @current_user.id, :completed => true)
  end


  private
  def check_if_logged_in
      redirect_to(root_path) if @current_user.nil?
  end

  def check_if_admin
      redirect_to(root_path) if @current_user.nil? || @current_user.admin == false
  end

  def error_test
    render :status => 404
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<h4>How do you rate this task?</h4>
<div class="category_button">
    <div class="first_group_button">
      <%= button_to "Urgent & Important", task_type_path(:category => "UI?#{params[:id]}"), :method => :get, :class => 'btn btn-warning buzz-out wobble-vertical', :id => 'newtask_button' %>
      <%= button_to "Urgent, Not Important", task_type_path(:category => "UNI?#{params[:id]}"), :method => :get, :class => 'btn btn-success buzz-out wobble-vertical', :id => 'newtask_button' %>
    </div>

    <div class="second_group_button">
      <%= button_to "Not Urgent, Important", task_type_path(:category => "NUI?#{params[:id]}"), :method => :get, :class => 'btn btn-info buzz-out wobble-vertical', :id => 'newtask_button' %>
      <%= button_to "Not Urgent, Not Important", task_type_path(:category => "NUNI?#{params[:id]}"), :method => :get, :class => 'btn btn-primary buzz-out wobble-vertical', :id => 'newtask_button' %>
    </div>
</div>

app/views/tasks/archive_by_category.html.erb
<div class="center-block">
    <h2><u>You have <%= pluralize(@archive_by_category.count, params[:category] + ' task') %> in archive!</u></h2>

    <% @archive_by_category.each do |task| %>
      <h2><%= link_to task.description, task_path(task.id), :class => "outline-inward" %></h2><hr class="style-two">
    <% end %>

    <br>
    <h4 class="ion-reply grow"><%= link_to('Back', tasks_archives_path) %></h4>

    <div id="user_link">
        <div class="center-block">
        <h1 class="outline-inward"><%= link_to('Current Tasks', tasks_categories_path) %></h1>
         &
        <h1 class="outline-inward"><%= link_to('Archives', tasks_archives_path) %></h1>
    </div>
</div>

app/views/tasks/archives_all.html.erb
<div class="center-block">
    <h2 class="lead"><u>All Your Archive Tasks</u></h2>

    <% @tasks.each do |task| %>
        <h2><%= link_to task.description, task_path(task.id), :class => "outline-inward" %></h2><hr class="style-two">
    <% end %>

    <br>
    <h4 class="ion-reply grow"><%= link_to('Back', tasks_archives_path) %></h4>

    <div id="user_link">
        <div class="center-block">
        <h1 class="outline-inward"><%= link_to('Current Tasks', tasks_categories_path) %></h1>
         &
        <h1 class="outline-inward"><%= link_to('Archives', tasks_archives_path) %></h1>
    </div>
</div>

app/views/tasks/categories.html.erb
<div>
    <kbd class="lead ">Your Current Tasks</kbd>

    <div class="list-group">
        <a href="/tasks/categories/all" class="list-group-item active">Show all</a>
        <a href="/tasks/UI/tasks_by_category" class="list-group-item">Urgent & Important</a>
        <a href="/tasks/UNI/tasks_by_category" class="list-group-item">Urgent, Not Important</a>
        <a href="/tasks/NUI/tasks_by_category" class="list-group-item">Not Urgent, Important</a>
        <a href="/tasks/NUNI/tasks_by_category" class="list-group-item">Not Urgent, Not Important</a>
    </div>

    <div id="user_link">
        <div class="center-block">
        <h1 class="outline-inward"><%= link_to('Current Tasks', tasks_categories_path) %></h1>
         &
        <h1 class="outline-inward"><%= link_to('Archives', tasks_archives_path) %></h1>
    </div>
</div>

app/views/tasks/categories_all.html.erb
<div class="center-block">
    <h2 class="lead"><u>All Your Current Tasks</u></h2>

    <% @tasks.each do |task| %>
        <h2 ><%= link_to task.description, task_path(task.id), :class => "outline-inward" %></h2><hr class="style-two">
    <% end %>

    <br>
    <h4 class="ion-reply grow"><%= link_to('Back', tasks_categories_path) %></h4>

    <div id="user_link">
        <div class="center-block">
        <h1 class="outline-inward"><%= link_to('Current Tasks', tasks_categories_path) %></h1>
         &
        <h1 class="outline-inward"><%= link_to('Archives', tasks_archives_path) %></h1>
    </div>
<div>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render :partial => 'form' %>

app/views/tasks/home.html.erb
<div class="center-block" id="">
    <kbd class="lead letter" id="tagline">Life is easier with Effy</kbd>
</div>

<div class="video-container center-block">
    <iframe scrolling="no" allowTransparency="true" frameborder="0" width="700" allowfullscreen height="450" src="http://goanimate.com/player/embed/0CP9Iq6mDYbQ"></iframe>
</div>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<% @tasks.each do |task| %>
    <%= link_to task.description, task_path(task.id) %>
<% end %>

app/views/tasks/index_by_category.html.erb
<div class="center-block">
    <h2 class=""><u>You have <%= pluralize(@tasks_by_category.count, params[:category] + ' task') %> to go!</u></h2>

    <% @tasks_by_category.each do |task| %>
      <h2><%= link_to task.description, task_path(task.id), :class => "outline-inward" %></h2><hr class="style-two">
    <% end %>

    <br>
    <h4 class="ion-reply grow"><%= link_to('Back', tasks_categories_path) %></h4>

    <div id="user_link">
        <div class="center-block">
        <h1 class="outline-inward"><%= link_to('Current Tasks', tasks_categories_path) %></h1>
         &
        <h1 class="outline-inward"><%= link_to('Archives', tasks_archives_path) %></h1>
    </div>
</div>

app/views/tasks/show.html.erb
<div>
    <div class="wobble-vertical">&lt; <%= @task.description %> &gt;</div><br>
    <div class="wobble-vertical" style="color:#4fa744;">Categorized as <%= @task.category %></div>
    <div class="wobble-vertical" style="color:#ff5c77;">is now <%= @task.completed ? "completed" : "an on going task" %>!</div>

    <hr class="style-two">
    <%= link_to '   Redo it', task_uncompleted_path(@task), :class => "ion-ios7-undo-outline grow" if @task.completed %>
    <br><%= link_to '   Edit', edit_task_path(@task), :class => "ion-edit grow" if @task.completed == false %>
    <br><%= link_to "   I've done it", task_completed_path(@task), :class => "ion-archive grow" if @task.completed == false %>
    <br>
    <h2 class="lead"> <%= @current_user.name %></h2>
</div>

app/views/tasks/task_input.html.erb
<div id="">
    <h3>You're almost done</h3>
    <div class="progress progress-striped active">
      <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 75%">
        <span class="sr-only">75% Complete</span>
      </div>
    </div>

    <br>
    <div class="center-block" id="task_input">
      <%= form_for @task do |f| %>
        <%= f.hidden_field :category, :value => @category %>
        <%= f.text_field :description, :required => true, :placeholder => ' Enter your task         eg: lunch date', :id => 'inputbox' %>
        <br><br>
        <%= f.submit class: 'uibutton'%>
      <% end %>
    </div>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>