config/routes.rb
Effy::Application.routes.draw do
  root :to => 'tasks#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/tasks/category/:category' => 'tasks#task_input', :as => :task_type
  get '/tasks/categories' => 'tasks#categories'
  get '/tasks/categories/all' => 'tasks#categories_all'
  get '/tasks/:category/tasks_by_category' => 'tasks#index_by_category', :as => :index_category
  get '/tasks/archives' => 'tasks#archives'
  get '/tasks/archives/all' => 'tasks#archives_all'
  get '/tasks/archives/:category' => 'tasks#archive_by_category'


  get '/tasks/:id/completed' => 'tasks#completed', :as => 'task_completed'
  get '/tasks/:id/uncompleted' => 'tasks#uncompleted', :as => 'task_uncompleted'
  # get '/' => 'tasks#new'
  resources :tasks, :users

  get '/404' => 'tasks#error_test'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  about           :text
#  image           :text
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  admin           :boolean          default(FALSE)
#  email           :string(255)
#  location        :string(255)
#

class User < ActiveRecord::Base
    attr_accessible :name, :about, :image, :password, :password_confirmation, :email, :location
    has_many :tasks

    has_secure_password
    # validates :name, :presence => true, length: { minimum: 6, maximum: 20 }, :uniqueness => { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]+\Z/, message: "only allows alphanumeric characters" }
    # validates :password, :presence => true, length: { minimum: 6, maximum: 20 }, format: { with: /\A[a-zA-Z0-9]+\Z/, message: "only allows alphanumeric characters" }
    validates :image, :presence => true
    validates :name, :presence => true, :length => { :minimum => 2 }
    validates :name, :uniqueness => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_if_logged_in, :except => [:create, :new]
  before_filter :check_if_admin, :only => [:index]

  def index
      @users = User.all
  end

  def new
      @user = User.new
  end

  def create
      @user = User.new params[:user]
      if @user.save
          session[:user_id] = @user.id
          redirect_to new_task_path
      else
          render :new
      end
  end

  def show
    # binding.pry
    @user = User.find @current_user.id
  end

  def update
    @user = @current_user
    user_info = params[:user]
    @user.image = user_info[:image]
    @user.about = user_info[:about]
    @user.email = user_info[:email]
    @user.location = user_info[:location]
    if (@user.save)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def edit
    @user = User.find @current_user.id
  end


  private
  def check_if_logged_in
      redirect_to(root_path) if @current_user.nil?
  end

  def check_if_admin
      redirect_to(root_path) if @current_user.nil? || @current_user.admin == false
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div>
    <h1>Update info <i class="ion-loading-a"></i></h1>
    <hr>
    <br>
    <% if @user.errors.any? %>
        <ul>
            <% @user.errors.full_messages.each do |error| %>
                <li><%= error %></li>
            <% end %>
        </ul>
    <% end %>

    <%= form_for @user do |f| %>
        <div class="form-group">
            <%= label_tag ' Image:', nil, :class => 'ion-ios7-camera' %>
            <%= f.url_field :image, :placeholder => 'url eg: http://www.example.com/pic', :class => 'form-control' %>
        </div>

        <div class="form-group">
            <%= label_tag ' About:', nil, :class => 'ion-heart' %>
            <%= f.text_area(:about, size: '100x5', :placeholder => 'write something about you', :class => 'form-control') %>
        </div>

        <div class="form-group">
            <%= label_tag ' Email:', nil, :class => 'ion-email' %>
            <%= f.email_field :email, :placeholder => 'optional', :class => 'form-control' %>
        </div>

        <div class="form-group">
            <%= label_tag ' Location:', nil, :class => 'ion-location' %>
            <%= f.text_field :location, :placeholder => 'eg: Sydney, Australia', :class => 'form-control' %>
        </div>

        <%= f.submit "Update", class: 'btn btn-success grow-rotate'%>
    <% end %>
</div>

app/views/users/index.html.haml
%ol
    - @users.each do |user|
        %li= user.name

app/views/users/new.html.haml
%div
    - if @user.errors.any?
        %ol
            - @user.errors.full_messages.each do |msg|
                %li= msg
                %hr.style-two

    %section.signup
        = form_for @user do |f|
            %div.form-group
                = f.text_field :name, :autofocus => true, :class => 'form-control', :placeholder => 'username'
            %div.form-group
                = f.url_field :image, :required => true, :class => 'form-control', :placeholder => 'Paste your image url here'
            %div.form-group
                = f.password_field :password, :class => 'form-control', :placeholder => 'password'
            %div.form-group
                = f.password_field :password_confirmation, :class => 'form-control', :placeholder => 're-enter password'

            = f.submit "Register", :class => 'btn btn-success'

app/views/users/show.html.erb
<div>
    <h2><strong>  <%= @user.name %></strong></h2>
    <hr class="style-two">

        <div class="user_first">
            <%= image_tag @user.image, :class => "user_image grow img-responsive" %>
        </div>
        <div class="user_second">
            <h5 class="lead" style="letter-spacing:1.5px;"><strong style="color:white;"><u>About: </u></strong><br><%= @user.about %></h5>
            <h5 class="lead" style="letter-spacing:1.5px;"><strong style="color:white;"><u>Email: </u></strong><br><%= @user.email %></h5>
            <h5 class="lead" style="letter-spacing:1.5px;"><strong style="color:white;"><u>Location: </u></strong><br><%= @user.location %></h5>
            <%= link_to '   Edit Profile', edit_user_path(@user), :class => "ion-edit btn btn-primary btn-sm grow-rotate" %>
        </div>

        <div id="user_link">
            <div class="center-block">
            <h1 class="outline-inward"><%= link_to('Current Tasks', tasks_categories_path) %></h1>
             &
            <h1 class="outline-inward"><%= link_to('Archives', tasks_archives_path) %></h1>
        </div>
        </div>

</div>